---
- hosts: database
  become: true
  tasks:
  - name: Pull mongo image
    community.docker.docker_image:
     name: mongo
     tag: latest
     source: pull

  - name: Run container
    community.docker.docker_container:
     name: mongo
     image: mongo:latest
     state: started
     ports: 27017:27017

    