---
- hosts: frontend
  become: true
  tasks:
    - name: Clone repo
      git:
        repo: https://github.com/keshav-raj-gautam/3-tier-azure-deployment.git
        dest: /home/keshav/wanderlust
        version: main
        update: yes
        force: true

    - name: Build frontend image
      community.docker.docker_image:
        name: frontend
        tag: latest
        state: present
        source: build
        build:
          path: /home/keshav/wanderlust/frontend

    - name: Run container
      community.docker.docker_container:
        name: frontend
        image: frontend:latest
        state: started
        ports:
          - "80:80"



 


