---
- hosts: all
  become: true
  tasks:
    - name: Ensure python3-pip is installed
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Ensure Docker SDK for Python is installed
      pip:
        name: docker
        executable: pip3